spring: 
  profiles:  
    active: 
	- dev
---
spring: 
  profiles: dev #开发环境
  application: 
    name: microservicecloud-config-ddtech-dev
---
spring: 
  profile: test #测试环境
  application:  
    name: microservicecloud-config-ddtech-test