spring: 
  profiles:  
    active: 
    - dev
---

server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.ddtech.springcloud.entitys    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   profiles: dev #开发环境
   application:
    name: microservicecloud-dept                                    #spring cloud 暴露的服务名称
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

 #eureka客服端注册
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka     
      defaultZone: http://eureka7001.com:7001/eureka/    
      
  #修改服务名称eureka中的服务信息
  instance:
    instance-id: microservicecloud-dept8001-dev
    prefer-ip-address: true     #访问路径可以显示IP地址 
   #info信息（微服务info信息（关于我们说明））
info: 
  app.name: ddtech-microservicecloud-config-dept-test
  company.name: www.ddtech.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.ddtech.springcloud.entitys    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   profiles: test #开发环境
   application:
    name: microservicecloud-dept                                    #spring cloud 暴露的服务名称
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

 #eureka客服端注册
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka     
      defaultZone: http://eureka7001.com:7001/eureka/    
      
  #修改服务名称eureka中的服务信息
  instance:
    instance-id: microservicecloud-dept8001-test
    prefer-ip-address: true     #访问路径可以显示IP地址 
   #info信息（微服务info信息（关于我们说明））
info: 
  app.name: ddtech-microservicecloud-config-dept-test
  company.name: www.ddtech.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$